#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="${ALTITUDE_RECIPE_OUT:-$ROOT/out/source-packages}"
WORK="${ALTITUDE_RECIPE_WORK:-$ROOT/out/source-work/evolution-data-server}"
JOBS="${JOBS:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 1)}"
VERSION=3.56.2
TARGET="${ALTITUDE_TARGET_TRIPLET:-x86_64-altitude-linux-gnu}"
TOOLCHAIN_ROOT="${ALTITUDE_TOOLCHAIN_ROOT:-}"
FORGE_ROOT="${ALTITUDE_FORGE_ROOT:-}"
TOOLCHAIN="$TOOLCHAIN_ROOT/opt/altitude/toolchain"
FORGE="$FORGE_ROOT/opt/altitude/forge"
SYSROOT="$TOOLCHAIN/sysroot"
CC="$TOOLCHAIN/bin/$TARGET-gcc"
CXX="$TOOLCHAIN/bin/$TARGET-g++"
AR="$TOOLCHAIN/bin/$TARGET-ar"
STRIP="$TOOLCHAIN/bin/$TARGET-strip"
PKG_CONFIG="$FORGE/bin/pkg-config"
PAYLOAD="$WORK/payload"
TARBALL="$(bash "$ROOT/scripts/source-fetch.sh" evolution-data-server)"

export PATH="$FORGE/bin:$TOOLCHAIN/bin:$PATH"
export PKG_CONFIG_LIBDIR="$SYSROOT/usr/lib/pkgconfig:$SYSROOT/usr/share/pkgconfig"
export PKG_CONFIG_SYSROOT_DIR="$SYSROOT"
export LD_LIBRARY_PATH="$SYSROOT/usr/lib:$SYSROOT/usr/lib64:$FORGE/lib:$TOOLCHAIN/$TARGET/lib64:${LD_LIBRARY_PATH:-}"

for tool in "$CC" "$CXX" "$AR" "$STRIP" "$PKG_CONFIG" cmake ninja; do
  command -v "$tool" >/dev/null || { echo "evolution-data-server: missing build tool: $tool" >&2; exit 1; }
done
for dep in glib-2.0 gio-2.0 gmodule-2.0 libsecret-1 libxml-2.0 libsoup-3.0 sqlite3 uuid json-glib-1.0 libical-glib nspr nss; do
  "$PKG_CONFIG" --exists "$dep" || { echo "evolution-data-server: target dependency missing: $dep" >&2; exit 1; }
done

rm -rf "$WORK"
mkdir -p "$WORK/source" "$WORK/build" "$PAYLOAD/usr/share/altitude/sources" "$OUT"
tar -xf "$TARBALL" -C "$WORK/source" --strip-components=1
sed -i 's/^if(NOT WITH_GOOGLE_CLIENT_ID STREQUAL "")/if(FALSE)/' "$WORK/source/data/CMakeLists.txt"

cat > "$WORK/toolchain.cmake" <<EOF
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER "$CC")
set(CMAKE_CXX_COMPILER "$CXX")
set(CMAKE_AR "$AR")
set(CMAKE_STRIP "$STRIP")
set(CMAKE_SYSROOT "$SYSROOT")
set(CMAKE_FIND_ROOT_PATH "$SYSROOT")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(ENV{PKG_CONFIG_LIBDIR} "$PKG_CONFIG_LIBDIR")
set(ENV{PKG_CONFIG_SYSROOT_DIR} "$SYSROOT")
EOF

cmake -S "$WORK/source" -B "$WORK/build" -G Ninja \
  -DCMAKE_TOOLCHAIN_FILE="$WORK/toolchain.cmake" \
  -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX= \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_EXE_LINKER_FLAGS="-Wl,-rpath-link,$SYSROOT/usr/lib -Wl,-rpath-link,$SYSROOT/usr/lib64 -Wl,-rpath-link,$SYSROOT/lib -Wl,-rpath-link,$SYSROOT/lib64" \
  -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-rpath-link,$SYSROOT/usr/lib -Wl,-rpath-link,$SYSROOT/usr/lib64 -Wl,-rpath-link,$SYSROOT/lib -Wl,-rpath-link,$SYSROOT/lib64" \
  -DENABLE_GTK=OFF -DENABLE_GTK4=OFF \
  -DENABLE_OAUTH2_WEBKITGTK=OFF -DENABLE_OAUTH2_WEBKITGTK4=OFF \
  -DENABLE_GOA=OFF -DENABLE_WEATHER=OFF -DENABLE_CANBERRA=OFF \
  -DENABLE_EXAMPLES=OFF -DENABLE_TESTS=OFF -DENABLE_INSTALLED_TESTS=OFF \
  -DENABLE_INTROSPECTION=OFF -DENABLE_VALA_BINDINGS=OFF \
  -DENABLE_GTK_DOC=OFF -DENABLE_GI_DOCGEN=OFF \
  -DENABLE_SMIME:BOOL=ON -DENABLE_SCHEMAS_COMPILE=OFF \
  -DWITH_KRB5=OFF -DWITH_OPENLDAP=OFF -DWITH_LIBDB=OFF \
  -D_correct_iconv_EXITCODE=0 -DHAVE_LKSTRFTIME_EXITCODE=0 \
  -DENABLE_BACKEND_PER_PROCESS=OFF -DENABLE_IPV6=ON

cat > "$WORK/build/iconv-detect.h" <<'EOF'
/* Generated by the Altitude cross-build recipe. */
#define ICONV_ISO_D_FORMAT "ISO-%d-%d"
#define ICONV_ISO_S_FORMAT "ISO-%d-%s"
#define ICONV_10646 "UCS-4BE"
EOF

cmake --build "$WORK/build" --parallel "$JOBS"
DESTDIR="$PAYLOAD" cmake --install "$WORK/build"

find "$PAYLOAD/usr" -type f -perm -0100 -print0 |
  while IFS= read -r -d '' file; do
    "$STRIP" --strip-unneeded "$file" 2>/dev/null || true
  done
cp -a "$PAYLOAD/usr/." "$SYSROOT/usr/"

{
  echo "Source: evolution-data-server"
  echo "Version: $VERSION"
  echo "SHA256: $(sha256sum "$TARBALL" | awk '{print $1}')"
  echo "Build: GNOME Shell calendar libraries, no GTK/OAuth/GOA/weather/tests, cross $TARGET"
  echo "Compiler: $("$CC" --version | head -1)"
} > "$PAYLOAD/usr/share/altitude/sources/evolution-data-server.build"

bash "$ROOT/rootfs/bin/altpkg-build" \
  "$ROOT/recipes/evolution-data-server/MANIFEST" "$PAYLOAD" \
  "$OUT/altitude-evolution-data-server-$VERSION-amd64.altpkg"
