bdbconf 1

# Typed registry
registry /system/desktop/enabled bool system false
registry /system/locale/keymap string system fr
registry /system/network/failover string netmgr carrier
registry /system/product/base string system altitude
registry /system/product/codename string system basecamp
registry /system/product/id string system altitude
registry /system/product/name string system Altitude Linux
registry /system/product/version string system 0.1.0
registry /system/package/manager string system altpkg
registry /system/package/registry string system altitude-main
registry /system/package/registry/enabled bool system true
registry /system/package/registry/url string system file:///var/lib/altitude/repository
registry /system/init/provider string system busybox-init
registry /system/init/systemd/compatible bool system true
registry /system/init/systemd/required bool system false

# Service graph
dependency accounts requires dbus
dependency displayd after graphical
dependency graphical after udevd
dependency graphical requires dbus
dependency graphical requires elogind
dependency graphical requires polkit
dependency netmgr requires dbus
dependency polkit requires dbus
dependency sshd after netmgr
dependency upower requires dbus
