bdbconf 1

# Typed registry
registry /system/desktop/enabled bool system true
registry /system/locale/keymap string system fr
registry /system/network/failover string netmgr carrier
registry /system/product/base string system altitude
registry /system/product/codename string system basecamp
registry /system/product/id string system altitude
registry /system/product/name string system Altitude Linux
registry /system/product/version string system 0.1.0
registry /system/package/manager string system altpkg
registry /system/package/registry string system altitude-main
registry /system/package/registry/enabled bool system true
registry /system/package/registry/url string system file:///var/lib/altitude/repository
registry /system/apps/registry string system app_registry
registry /system/apps/source string system desktop-files
registry /system/apps/autorefresh bool system true
registry /system/systemd/audit/enabled bool system true
registry /system/systemd/audit/table string system systemd_audit
registry /system/systemd/audit/control bool system false
registry /system/systemd/runtime/present bool system true
registry /system/systemd/runtime/pid1 bool system true
registry /system/init/provider string system systemd
registry /system/init/systemd/required bool system true
registry /system/registry/audit/enabled bool system true
registry /system/registry/audit/owner string system registry-audit
