bdbconf 1

# Typed registry
registry /system/desktop/enabled bool system true
registry /system/locale/keymap string system fr
registry /system/network/failover string netmgr carrier

# Service graph
dependency accounts requires dbus
dependency displayd after graphical
dependency graphical after udevd
dependency graphical requires dbus
dependency graphical requires elogind
dependency graphical requires polkit
dependency netmgr requires dbus
dependency polkit requires dbus
dependency sshd after netmgr
dependency upower requires dbus
